// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.19.4
// source: shopCart.proto

package shopCart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加购物车
type AddShopCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GoodsId       uint64                 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	Num           uint64                 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShopCartRequest) Reset() {
	*x = AddShopCartRequest{}
	mi := &file_shopCart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShopCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShopCartRequest) ProtoMessage() {}

func (x *AddShopCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShopCartRequest.ProtoReflect.Descriptor instead.
func (*AddShopCartRequest) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{0}
}

func (x *AddShopCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddShopCartRequest) GetGoodsId() uint64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *AddShopCartRequest) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AddShopCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShopCartResponse) Reset() {
	*x = AddShopCartResponse{}
	mi := &file_shopCart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShopCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShopCartResponse) ProtoMessage() {}

func (x *AddShopCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShopCartResponse.ProtoReflect.Descriptor instead.
func (*AddShopCartResponse) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{1}
}

// 查看购物车
type ShopCartListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Page          uint64                 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartListRequest) Reset() {
	*x = ShopCartListRequest{}
	mi := &file_shopCart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartListRequest) ProtoMessage() {}

func (x *ShopCartListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartListRequest.ProtoReflect.Descriptor instead.
func (*ShopCartListRequest) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{2}
}

func (x *ShopCartListRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShopCartListRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ShopCartListRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShopCartListRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ShopCartList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint64                 `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	GoodsImage    string                 `protobuf:"bytes,2,opt,name=GoodsImage,proto3" json:"GoodsImage,omitempty"`
	GoodsName     string                 `protobuf:"bytes,3,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	GoodsPrice    float32                `protobuf:"fixed32,4,opt,name=GoodsPrice,proto3" json:"GoodsPrice,omitempty"`
	Num           uint64                 `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	TotalPrice    uint64                 `protobuf:"varint,6,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartList) Reset() {
	*x = ShopCartList{}
	mi := &file_shopCart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartList) ProtoMessage() {}

func (x *ShopCartList) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartList.ProtoReflect.Descriptor instead.
func (*ShopCartList) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{3}
}

func (x *ShopCartList) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ShopCartList) GetGoodsImage() string {
	if x != nil {
		return x.GoodsImage
	}
	return ""
}

func (x *ShopCartList) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *ShopCartList) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *ShopCartList) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ShopCartList) GetTotalPrice() uint64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type ShopCartListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ShopCartList        `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartListResponse) Reset() {
	*x = ShopCartListResponse{}
	mi := &file_shopCart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartListResponse) ProtoMessage() {}

func (x *ShopCartListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartListResponse.ProtoReflect.Descriptor instead.
func (*ShopCartListResponse) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{4}
}

func (x *ShopCartListResponse) GetList() []*ShopCartList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ShopCartListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 修改购物车
type UpdateShopCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GoodsId       uint64                 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	Num           uint64                 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShopCartRequest) Reset() {
	*x = UpdateShopCartRequest{}
	mi := &file_shopCart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShopCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopCartRequest) ProtoMessage() {}

func (x *UpdateShopCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopCartRequest.ProtoReflect.Descriptor instead.
func (*UpdateShopCartRequest) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateShopCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateShopCartRequest) GetGoodsId() uint64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *UpdateShopCartRequest) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UpdateShopCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShopCartResponse) Reset() {
	*x = UpdateShopCartResponse{}
	mi := &file_shopCart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShopCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopCartResponse) ProtoMessage() {}

func (x *UpdateShopCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopCartResponse.ProtoReflect.Descriptor instead.
func (*UpdateShopCartResponse) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{6}
}

// 购物车结算
type ShopCartCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartCheckoutRequest) Reset() {
	*x = ShopCartCheckoutRequest{}
	mi := &file_shopCart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartCheckoutRequest) ProtoMessage() {}

func (x *ShopCartCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartCheckoutRequest.ProtoReflect.Descriptor instead.
func (*ShopCartCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{7}
}

func (x *ShopCartCheckoutRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ShopCartCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayUrl        string                 `protobuf:"bytes,1,opt,name=PayUrl,proto3" json:"PayUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartCheckoutResponse) Reset() {
	*x = ShopCartCheckoutResponse{}
	mi := &file_shopCart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartCheckoutResponse) ProtoMessage() {}

func (x *ShopCartCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopCart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartCheckoutResponse.ProtoReflect.Descriptor instead.
func (*ShopCartCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_shopCart_proto_rawDescGZIP(), []int{8}
}

func (x *ShopCartCheckoutResponse) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

var File_shopCart_proto protoreflect.FileDescriptor

var file_shopCart_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x68,
	0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x22, 0x15, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6f, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xb6, 0x01, 0x0a, 0x0c, 0x53, 0x68,
	0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x22, 0x55, 0x0a, 0x14, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5b, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x31, 0x0a, 0x17, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x18, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x32, 0xc0, 0x02, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x74, 0x53, 0x72, 0x76, 0x12, 0x44, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x53, 0x68,
	0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f,
	0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x0c, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x73, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shopCart_proto_rawDescOnce sync.Once
	file_shopCart_proto_rawDescData = file_shopCart_proto_rawDesc
)

func file_shopCart_proto_rawDescGZIP() []byte {
	file_shopCart_proto_rawDescOnce.Do(func() {
		file_shopCart_proto_rawDescData = protoimpl.X.CompressGZIP(file_shopCart_proto_rawDescData)
	})
	return file_shopCart_proto_rawDescData
}

var file_shopCart_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shopCart_proto_goTypes = []any{
	(*AddShopCartRequest)(nil),       // 0: proto.AddShopCartRequest
	(*AddShopCartResponse)(nil),      // 1: proto.AddShopCartResponse
	(*ShopCartListRequest)(nil),      // 2: proto.ShopCartListRequest
	(*ShopCartList)(nil),             // 3: proto.ShopCartList
	(*ShopCartListResponse)(nil),     // 4: proto.ShopCartListResponse
	(*UpdateShopCartRequest)(nil),    // 5: proto.UpdateShopCartRequest
	(*UpdateShopCartResponse)(nil),   // 6: proto.UpdateShopCartResponse
	(*ShopCartCheckoutRequest)(nil),  // 7: proto.ShopCartCheckoutRequest
	(*ShopCartCheckoutResponse)(nil), // 8: proto.ShopCartCheckoutResponse
}
var file_shopCart_proto_depIdxs = []int32{
	3, // 0: proto.ShopCartListResponse.List:type_name -> proto.ShopCartList
	0, // 1: proto.ShopCartSrv.AddShopCart:input_type -> proto.AddShopCartRequest
	2, // 2: proto.ShopCartSrv.ShopCartList:input_type -> proto.ShopCartListRequest
	5, // 3: proto.ShopCartSrv.UpdateShopCart:input_type -> proto.UpdateShopCartRequest
	7, // 4: proto.ShopCartSrv.ShopCartCheckout:input_type -> proto.ShopCartCheckoutRequest
	1, // 5: proto.ShopCartSrv.AddShopCart:output_type -> proto.AddShopCartResponse
	4, // 6: proto.ShopCartSrv.ShopCartList:output_type -> proto.ShopCartListResponse
	6, // 7: proto.ShopCartSrv.UpdateShopCart:output_type -> proto.UpdateShopCartResponse
	8, // 8: proto.ShopCartSrv.ShopCartCheckout:output_type -> proto.ShopCartCheckoutResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shopCart_proto_init() }
func file_shopCart_proto_init() {
	if File_shopCart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shopCart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopCart_proto_goTypes,
		DependencyIndexes: file_shopCart_proto_depIdxs,
		MessageInfos:      file_shopCart_proto_msgTypes,
	}.Build()
	File_shopCart_proto = out.File
	file_shopCart_proto_rawDesc = nil
	file_shopCart_proto_goTypes = nil
	file_shopCart_proto_depIdxs = nil
}
